import {useState,useEffect,useRef} from 'react';
import {Link} from 'react-router-dom';
import MineMap from '../minetwin/MineMap';
import {STATES,metricState,stageState,format,clock,EVENTS,snapshot,equipment,compare,alertMetric,lotState,fleetSummary} from '../minetwin/scenario';
import './MineTwin.css';
const guide=['Detecta la brecha en molienda','Explora los equipos de carguío','Sigue el lote B-12 hasta planta','Revisa evidencia y explicaciones','Compara una recuperación y registra la revisión'];
function Trend({id,t}) {
 const [hover,setHover]=useState(null);
 const events=EVENTS.filter(e=>e.stage===id&&e.t<=t);
 const times=[...new Set([0,t,...Array.from({length:7},(_,i)=>Math.round(t*i/6)),...events.flatMap(e=>[Math.max(0,e.t-1),e.t])])].sort((a,b)=>a-b);
 const index=id==='blast'?1:0;
 const metricAt=time=>snapshot(time).stages.find(s=>s.id===id).metrics[index];
 const values=times.map(time=>metricAt(time).actual),m=metricAt(t);
 const lo=Math.min(...values,m.target)*.8,hi=Math.max(...values,m.target)*1.1||1;
 const x=time=>38+time/Math.max(1,t)*270,y=v=>100-(v-lo)/(hi-lo)*70;
 const labels={0:'Inicio',30:'B-12 liberado',60:'Carguío B-12',90:'B-12 en chancado',120:'PAL-03 detenida',180:'B-12 en SAG',240:'PAL-03 recuperada'};
 return <div className="m2-trend"><b>{m.name} · {m.unit}</b>
 <svg viewBox="0 0 330 144" role="img" aria-label={`Tendencia desde 06:00 hasta ${clock(t)}. Actual ${format(m.actual)}; meta ${format(m.target)}`}>
 <path d={`M38 ${y(m.target)}H308`} stroke="#8ea891" strokeDasharray="4 4"/>
 {events.map(e=><g key={e.t}><path d={`M${x(e.t)} 25V106`} stroke="#819b85" strokeDasharray="2 5"/><circle cx={x(e.t)} cy="19" r="4" fill="#dfbd7f"><title>{clock(e.t)} · {labels[e.t]}</title></circle></g>)}
 <polyline points={values.map((v,i)=>`${x(times[i])},${y(v)}`).join(' ')} fill="none" stroke="#dfbd7f" strokeWidth="2.5"/>
 {values.map((v,i)=><circle key={times[i]} cx={x(times[i])} cy={y(v)} r="4" fill="#dfbd7f" tabIndex="0" role="button" aria-label={`${clock(times[i])}: ${format(v)} ${m.unit}`} onMouseEnter={()=>setHover(times[i])} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(times[i])} onBlur={()=>setHover(null)}><title>{clock(times[i])}: {format(v)} {m.unit}</title></circle>)}
 <text x="0" y="15" fill="#aec0ae" fontSize="12">{format(Math.round(hi))}</text><text x="0" y="114" fill="#aec0ae" fontSize="12">{format(Math.round(lo))}</text><text x="38" y="138" fill="#aec0ae" fontSize="12">06:00</text><text x="274" y="138" fill="#aec0ae" fontSize="12">{clock(t)}</text></svg>
 <p className="m31-trend-readout" aria-live="polite">{hover!==null&&hover<=t?`${clock(hover)} · ${format(metricAt(hover).actual)} ${m.unit}`:`${clock(t)} · ${format(m.actual)} ${m.unit}`}</p>
 <small>Referencia: {format(m.target)} {m.unit} · {id==='drill'?'Meta acumulada al corte.':'Datos sintéticos.'}</small>
 <div className="m31-event-legend">{events.map(e=><span key={e.t}><b>{clock(e.t)}</b> {labels[e.t]}</span>)}</div></div>
}
export default function MineTwin(){
 const [t,setT]=useState(240),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(5),[selected,setSelected]=useState('grind'),[tab,setTab]=useState('Indicadores'),[asset,setAsset]=useState(null),[actions,setActions]=useState([]),[hours,setHours]=useState(6),[recovery,setRecovery]=useState(75),[tour,setTour]=useState(-1);
 const map=useRef(null),dialog=useRef(null); const data=snapshot(t),stage=data.stages.find(s=>s.id===selected),fleet=equipment(selected,t),status=stageState(stage),comparison=compare(t,hours,recovery); const gap=2336-data.grind;
 useEffect(()=>{const old=document.title;document.title='DATOT MineTwin · Simulación operacional';return()=>{document.title=old}},[]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setT(x=>Math.min(360,x+speed)),1000);return()=>clearInterval(timer)},[playing,speed]);
 useEffect(()=>{if(t===360)setPlaying(false)},[t]);
 function select(id,focus=false){setSelected(id);setAsset(null);if(focus)map.current?.focus(id)}
 function guided(n){setTour(n);setPlaying(false);setT(210);const ids=['grind','load','grind','grind','grind'];select(ids[n],true);setTab(['Indicadores','Equipos','Material','Análisis','Escenarios'][n])}
 function reset(){setPlaying(false);setT(0);setActions([]);setTour(-1);setAsset(null);map.current?.reset()}
 return <div className="m2-app"><header className="m2-header"><div className="m2-brand"><span className="m2-logo">D·</span><div><strong>DATOT <b>MineTwin</b></strong><small>DIGITAL OPERATIONS CENTER / V5.2</small></div></div><div className="m2-header-context">DE LA MINA A LA MOLIENDA</div><div className="m2-header-actions"><span className="m2-demo-indicator">DEMO SINTÉTICA</span><button onClick={()=>dialog.current.showModal()}>Acerca de</button><Link to="/">← Portafolio</Link></div></header>
 <main className="m2-main"><section className="m2-intro"><div><span className="m2-eyebrow">OPERACIÓN A TAJO ABIERTO / TURNO A</span><h1>Una operación. <em>Todo conectado.</em></h1><p>Explora equipos, sigue el mineral y compara decisiones.</p></div><button className="m2-primary" onClick={()=>guided(0)}>Iniciar recorrido guiado →</button></section>
 <section className="m3-alert" role="status"><div><span className="m2-eyebrow">{gap>0?'ATENCIÓN PRIORITARIA / MOLIENDA':'OPERACIÓN / REFERENCIA'}</span><strong>{gap>0?`${format(gap)} t/h por debajo de la referencia`:'Molienda en referencia: 2,336 t/h'}</strong><span>{gap>0?`Desviación desde 09:00 · ${t-180} min · Brecha acumulada del modelo: ${format(data.deficit)} t`:'Avanza el reloj para descubrir los eventos del turno.'}</span></div><div><strong>{format(data.inventory)} t</strong><span>En acopio · balance desde 1,800 t iniciales</span></div><button onClick={()=>{select('grind',true);setTab('Análisis')}}>Investigar →</button></section>
 <section className="m3-timeline" aria-label="Control de simulación"><button className="m2-primary" onClick={()=>{if(t===360)setT(0);setPlaying(v=>!v)}}>{playing?'Pausar':'Reproducir'}</button><strong>{clock(t)}</strong><input aria-label="Minuto del turno" type="range" min="0" max="360" value={t} onChange={e=>{setPlaying(false);setT(+e.target.value)}}/><select aria-label="Velocidad de simulación" value={speed} onChange={e=>setSpeed(+e.target.value)}><option value="1">1 min/s</option><option value="5">5 min/s</option><option value="15">15 min/s</option></select><button onClick={reset}>Reiniciar</button><small>06:00–12:00 · reloj simulado</small></section>
 {tour>=0&&<div className="m3-tour"><span>PASO {tour+1}/5 · {guide[tour]}</span><button onClick={()=>tour<4?guided(tour+1):setTour(-1)}>{tour<4?'Siguiente →':'Finalizar'}</button><button onClick={()=>setTour(-1)}>Cerrar guía</button></div>}
 <div className="m2-layout"><section className="m2-map-card"><div className="m2-map-bar"><div><span className="m2-eyebrow">01 / EXPLORA EL TERRITORIO</span><h2>Mapa de operaciones <span>· selecciona una etapa</span></h2></div><span>{data.stages.filter(s=>['warning','critical'].includes(stageState(s))).length} {data.stages.filter(s=>['warning','critical'].includes(stageState(s))).length===1?'etapa':'etapas'} en atención</span></div><MineMap ref={map} selected={selected} onSelect={id=>select(id)} animate={playing} stages={data.stages} minute={t}/><nav className="m2-chain" aria-label="Etapas">{data.stages.map(s=><div className="m2-chain-item" key={s.id}><button className={selected===s.id?'active':''} onClick={()=>select(s.id,true)}><span className={`m2-chain-number ${stageState(s)}`}>{s.number}</span><span>{s.name}<small>{s.id==='blast'?`${equipment(s.id,t).length} disponibles en espera`:`${equipment(s.id,t).filter(e=>e.state==='Operando').length}/${equipment(s.id,t).length} operando`} · {STATES[stageState(s)].label}</small></span></button></div>)}</nav><div className="m2-map-footer">Lote B-12 · {lotState(t)} · Corte {clock(t)}</div></section>
 <aside className="m2-panel"><span className="m2-eyebrow">02 / CONTEXTO DE LA ETAPA</span><div className="m2-stage-heading"><h2>{stage.name}</h2><span className={`m2-badge ${status}`}>{STATES[status].label}</span></div><p className="m2-zone">{selected==='blast'?`Bloque B-12 · ${lotState(t)}`:stage.zone} · {clock(t)}</p><button className="m31-fleet-summary" onClick={()=>setTab('Equipos')} aria-label="Ver estados de equipos">{fleetSummary(selected,t)} <span>Ver equipos →</span></button>
 {['warning','critical'].includes(status)&&<div className={`m31-reason ${status}`}><b>Motivo del semáforo</b><span>{alertMetric(stage).name}: {format(alertMetric(stage).actual)} {alertMetric(stage).unit} · meta {format(alertMetric(stage).target)}.</span>{selected==='drill'&&<small>PER-02 en mantenimiento programado reduce la disponibilidad de la etapa.</small>}</div>}
 <div className="m3-tabs" aria-label="Vistas de etapa">{['Indicadores','Equipos','Material','Análisis','Escenarios'].map(x=><button key={x} aria-pressed={tab===x} onClick={()=>setTab(x)}>{x==='Escenarios'?'Simular SAG':x}</button>)}</div>
 {tab==='Indicadores'&&<><div className="m2-metrics">{stage.metrics.map(m=><div className="m2-metric" key={m.name}><div className="m2-metric-top"><span>{m.name}</span><span className={`m2-metric-status ${metricState(m)}`}>{STATES[metricState(m)].label}</span></div><div className="m2-metric-value"><strong>{m.pending ? (m.name==='Mineral liberado'?'0':'—') : format(m.actual)} <small>{m.unit}</small></strong><span>Meta {m.direction==='up'?'≥':'≤'} {format(m.target)}</span></div><div className="m2-metric-bottom"><span>{m.window}</span></div>{metricState(m)==='normal'&&((m.direction==='up'&&m.actual<m.target)||(m.direction==='down'&&m.actual>m.target))&&<small>Dentro de tolerancia; meta aún no alcanzada.</small>}</div>)}</div><details className="m3-box"><summary>Metas y tolerancias de la demo</summary>{stage.metrics.map(m=><p key={m.name}>{m.name}: atención {m.direction==='up'?'por debajo de':'por encima de'} {format(m.target*m.warn)} {m.unit}; crítico {m.direction==='up'?'por debajo de':'por encima de'} {format(m.target*m.critical)} {m.unit}. Igualdad en límite crítico: atención.</p>)}<p>Estado de desempeño, no diagnóstico de falla. Umbrales ilustrativos.</p></details>{selected==='blast'&&t<30?<p className="m3-box">Bloque en preparación: 68,000 t previstas; 0 t liberadas. Fragmentación pendiente de evaluación.</p>:<Trend id={selected} t={t}/>}<button className="m2-primary" onClick={()=>setTab('Equipos')}>Explorar {fleet.length} equipos →</button></>}
 {tab==='Equipos'&&<><p>{fleet.filter(e=>e.state==='Operando').length} operando · {fleet.filter(e=>e.state==='Disponible en espera').length} en espera · {fleet.filter(e=>e.state.includes('falla')).length} en falla · {fleet.filter(e=>e.state.includes('programado')).length} en mantenimiento</p>{fleet.map(e=><button key={e.id} className={`m3-equipment ${asset===e.id?'active':''}`} onClick={()=>setAsset(e.id)}><b>{e.id}</b><span>{e.state}</span><small>Disponibilidad {format(e.availability)} % · Utilización {e.utilization} %</small></button>)}{asset&&(()=>{const e=fleet.find(x=>x.id===asset);return <div className="m3-box"><h3>{e.id}</h3><p>{e.reason}</p><p>Tiempo no disponible: {e.down} min desde 06:00.</p>{e.capacity&&<p>Capacidad comprometida durante la falla: {e.capacity} t/h. El acopio absorbe parte del déficit; el efecto no es inmediato en SAG.</p>}<p>Revisar estado, bitácora y asignación antes de atribuir una pérdida.</p></div>})()}<details className="m3-box"><summary>Definiciones y funciones</summary><p>Disponibilidad = (minutos del turno − minutos no disponibles) / minutos del turno. Incluye mantenimiento programado. Al inicio se muestra el estado inicial.</p><p>Utilización = tiempo operando / tiempo disponible. Supuesto sintético: 90 % para equipos activos y 0 % para espera; no deriva de telemetría.</p><p>PER: perforadora · UCE: unidad de carga de explosivos · PAL: pala · CAR: cargador · CH: chancadora · ALI: alimentador · FAJ: faja · SAG/BM: molinos · P: bomba.</p></details></>}
 {tab==='Material'&&<><div className="m3-box"><span className="m2-eyebrow">LOTE B-12 / TRAZABILIDAD</span><h3>{lotState(t)}</h3><p>Bloque B-12 → PAL-01 → transporte (30 min) → CH-01 → acopio (90 min) → SAG-01.</p><p>P80 de origen: {t<30?'Pendiente':'245 mm'} · Mezcla pedagógica: {t<180?'B-11 en SAG':`${Math.round(Math.min(1,(t-180)/60)*100)} % B-12 en SAG`}.</p><p>B-13 sigue en perforación; no se convierte en el lote B-12 durante este turno.</p></div><div className="m3-box"><h3>Acopio · {format(data.inventory)} t</h3><p>Entrada: {format(Math.min(data.input,data.crush))} t/h<br/>Salida SAG: {format(data.grind)} t/h<br/>Balance: {format(Math.min(data.input,data.crush)-data.grind)} t/h</p><p>Inventario inicial 1,800 t + entradas − salidas. Permanencia y mezcla impuestas para enseñar retrasos; no es un modelo físico de segregación.</p></div></>}
 {tab==='Análisis'&&<><div className="m3-box"><h3>Observación · {stage.name}</h3><p>{stage.metrics[0].name}: {format(stage.metrics[0].actual)} {stage.metrics[0].unit} frente a {format(stage.metrics[0].target)}.</p><h3>Evidencia del escenario</h3>{EVENTS.filter(e=>e.t<=t).map(e=><button className="m3-event" key={e.t} onClick={()=>{select(e.stage,true);setT(e.t);setPlaying(false)}}><b>{clock(e.t)}</b> {e.text}</button>)}<h3>Hipótesis y alternativas</h3><p>{t>=180?'La llegada de B-12 coincide con la caída de tratamiento; el modelo impone esa relación para la demostración. En una operación real habría que verificar dureza, granulometría, alimentación y condición mecánica.':'Todavía no existe evidencia temporal para atribuir una caída del SAG al lote B-12.'}</p><p>Verificación: comparar lotes, distribución granulométrica, potencia, alimentación y registro de paradas. Coincidencia no confirma causa.</p></div><button className="m2-primary" onClick={()=>setActions(a=>[...a,{id:Date.now(),stage:selected,time:t,state:'Pendiente',baseline:stage.metrics[0].actual}])}>Registrar revisión simulada</button>{actions.filter(a=>a.stage===selected).map(a=><div className="m3-box" key={a.id}><b>Operaciones · {clock(a.time)}</b><select aria-label="Estado de revisión" value={a.state} onChange={e=>setActions(all=>all.map(x=>x.id===a.id?{...x,state:e.target.value}:x))}>{['Pendiente','En revisión','Completada'].map(x=><option key={x}>{x}</option>)}</select><p>Valor al registro: {format(a.baseline)} · Ahora: {format(stage.metrics[0].actual)} {stage.metrics[0].unit}.</p><small>Registro local de sesión. Cerrar una revisión no modifica el escenario ni acredita recuperación.</small></div>)}</>}
 {tab==='Escenarios'&&<><div className="m3-box"><span className="m2-eyebrow">COMPARACIÓN / MOLIENDA</span><h3>¿Cuánto tratamiento podríamos recuperar?</h3><label>Horizonte: {hours} h<input aria-label="Horizonte en horas" type="range" min="1" max="12" value={hours} onChange={e=>setHours(+e.target.value)}/></label><label>Recuperar {recovery} % de la brecha<input aria-label="Porcentaje de recuperación" type="range" min="0" max="100" step="5" value={recovery} onChange={e=>setRecovery(+e.target.value)}/></label><p>Brecha actual: {format(gap)} t/h. Si persiste: {format(gap*hours)} t por debajo de referencia en {hours} h.</p><div className="m3-comparison"><div>Continuidad<strong>{format(comparison.base)} t</strong></div><div>Alternativa<strong>{format(comparison.alternative)} t</strong></div></div><h3>+{format(comparison.gain)} t potenciales</h3><p>Recuperación lineal durante 1 h y luego estable. Diferencia adicional de salida del acopio: {format(comparison.gain)} t si las entradas no cambian.</p><p>Energía a igual consumo específico ({format(stage.id==='grind'?stage.metrics[1].actual:snapshot(t).stages[4].metrics[1].actual)} kWh/t): +{format(comparison.gain*snapshot(t).stages[4].metrics[1].actual)} kWh. Es un supuesto, no una optimización energética.</p><small>Modelo aritmético condicionado; no predicción validada. La comparación no altera el turno ni verifica factibilidad de inventario futuro.</small></div><button className="m2-primary" onClick={()=>{select('grind');setTab('Análisis')}}>Registrar y seguir revisión →</button></>}
 </aside></div><footer className="m2-footer"><span>DATOT MineTwin / Datos, metas, equipos y escenarios sintéticos · Sin conexión a planta</span><span>EXPLORAR → COMPRENDER → DECIDIR</span></footer></main>
 <dialog className="m2-dialog" ref={dialog}><h2>MineTwin V5.2 · Alcance de la demo</h2><p>Modelo didáctico determinista, sin datos privados, telemetría, IA diagnóstica ni conexión Fabric. Los lotes, relaciones y eventos son supuestos explícitos.</p><p>Las cifras de capacidad, disponibilidad, mezcla y energía no son criterios de operación. Los eventos de recuperación están programados; ninguna revisión controla equipos.</p><p>Los registros duran hasta recargar o reiniciar. La simulación comienza pausada y respeta la preferencia de movimiento reducido.</p><form method="dialog"><button className="m2-primary">Cerrar</button></form></dialog></div>
}
